### ISSUE TITLE
调整配置文件格式

### ISSUE THREAD

**Issue by Colsrch** [MadokaProject/Madoka#51]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。

### 需求描述

使用 `yaml` 格式，为后续多账号做准备，每个单独一份配置

 ### 规范

- 某个配置可以拥有多条参数时，应以复数命名
- 某个配置只有单条参数时，应以单数命名

### 参考信息

```yaml
bots:
  - account:
      qq: 123456
      key: abc
      name: xx
      master: 1234567
    other_config: ...
  - account:
      ...
      ...
  - account: ...

```
